inhibit_all_warnings!
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'FishFinishing' do
    pod 'YTKNetwork'
    pod 'Mantle'
    pod 'MagicalRecord'
    pod 'libextobjc'
    pod 'ReactiveObjC',  '~> 3.1.0'
    pod 'LCProgressHUD'
    pod 'SDWebImage'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'IQKeyboardManager'
    pod 'HMSegmentedControl'
    pod 'CQTopBar'
end

target 'FishFinishingTests' do
  pod 'Expecta'
end
